### PR TITLE
Add postgresql chart

### PR DESCRIPTION
**Pull request by badrange**

### CODE REVIEW

**Review by Jancis — APPROVED** [review]
Looks good, accepted! I'll add a link to subchart's values file as a comment for the configuration block.

**Comment by badrange** [comment]
> I had to roll it back due to it's library chart (common) clash with mongodb that also comes from bitnami. I'll see what I can do about it and then release it later.

Ah, thank you for the heads up. 

> Did You also check out the HA version of postgres subchart? Any idea if it can be scaled down by default and then offer a reasonably stable HA solution in production? I have not tested either, but at least with the mariadb HA solutions so far I was able to crash replication to a broken state so I am not too sure about postgres, but maybe it's still a viable solution.

I looked at it briefly and considered adding that, I just don't know how far into the future it will be necessary for us to start thinking about replication so I decided to go for the simplest solution first.

It might be a good idea to start looking into replication already now even though we don't need it for performance: Could be nice for resilience.

**Comment by Jancis** [comment]
Followup - postgres support was merged

**Comment by badrange** [comment]
Nice! Now we need to find the time to try it out!

**Pull request merged**
